### ISSUE TITLE
Cannot find the ulibm3ua repository

### ISSUE THREAD

**Issue by sumeetchhetri** [andreasfink/ulib#1]
Hi Andreas,

I did not find the ulibm3ua repository in your repository list, but i see that you have mentioned that in your README, is it commercial like the messagemover?

**Comment by andreasfink** [comment]
ulibm3ua used to be a planned library to be ported out of messagemover. However it turned out to be easier to implement it in ulibmtp3 so a separate library became obsolete.

Release 1.8 (currently trunk) has ulibm3ua support now and it works well in my production environment. I'm working heavily on MTP3 forwarding (almost complete) and SCCP routing (still work to do). And there might be a ulibisup if theres enough demand.
