### ISSUE TITLE
Install sctp framework in MacOS High Sierra

### ISSUE THREAD

**Issue by sumeetchhetri** [andreasfink/ulib#2]
Hi Andreas,

Are there any instructions on how to install SCTP (https://github.com/sctplab/SCTP_NKE_HighSierra) as a framework in MacOS. I am actually new to Mac. I followed instructions provided on the project page and installed headers to /us/include and /usr/lib, but on Mac ulib looks for headers/library in the /Library/Framework/sctp.framework folder. Any instructions to build ulib on Mac would be really helpful. I tried working around by creating a folder manually and moving headers there but the build fails when it is unable to find the sctp framework during linking(ld: framework not found sctp)

Thanks,
Sumeet

**Comment by andreasfink** [comment]
> On 29 May 2018, at 19:56, Sumeet Chhetri <notifications@github.com> wrote:
> 
> Hi Andreas,
> 
> Are there any instructions on how to install SCTP (https://github.com/sctplab/SCTP_NKE_HighSierra <https://github.com/sctplab/SCTP_NKE_HighSierra>) as a framework in MacOS. I am actually new to Mac. I followed instructions provided on the project page and installed headers to /us/include and /usr/lib, but on Mac ulib looks for headers/library in the /Library/Framework/sctp.framework folder. Any instructions to build ulib on Mac would be really helpful. I tried working around by creating a folder manually and moving headers there but the build fails when it is unable to find the sctp framework during linking(ld: framework not found sctp)
> 
> Thanks,
> Sumeet
> 
> 

The framework vs library is easy.

A frameworks is a so called bundle. A bundle which puts together shared library, header files and other resource file in a organized structure
I built it the way that it goes into /Library/Frameworks as shown below. The problem on the mac is if you put the netinet/sctp.h and netinet/sctp_uio.h into /usr/include/, then xcode wont find it as it will look for header files in the MacOS X SDK directory. The SDK is basically a stub version on whats on a empty system. You can have different SDKs as you might want to compile code which runs on 10.10 but you compile it on 10.13 etc. So the SDK decides which libraries to compile against.

Secondly. even if you put the files into the SDK, they might not survive the next Xcode update. So the more comfortable solution is to have a Framework which you can drag and drop into a project. You can either have it installed under /Library/Frameworks system wide or an App could have it built in its own bundle (but you still need the kernel extension for that to work(

The file in the framework bundle is not in any wayndifferent to a shared library file. So this is not a question of compiling, this is a question of packaging it.
The .PKG installer file in the repository also has a small change to the netinet/sctp.h file.
Instead of including <netinet/sctp_uio.h> in it (which will look for sctp_uio.h in /usr/include/netinet/), it uses #include "sctp_uio.h" which is the same directory as sctp.h. So that always works.
However the current PKG file has an error because there's two places where sctp_uio.h is included and I only changed one. So if you install the PKG to use SCTP, you have to change that.
I will rebuild the current PKG soon to fix this.

So the quickest way is to install the PKG with

sudo installer -pkg SCTP_HighSierra_201802141612.pkg -target /

and then edit /Library/Frameworks/sctp.framework/Versions/A/Headers/sctp.h

to include "sctp_uio.h" instead of <netinet/sctp_uio.h>

Then you can simply drag & drop the SCTP.framework into a Xcode project (or you can use --framework SCTP on the command line instead of the include files.
To use it from your code you would include it this way

#include <sctp/sctp.h>

which will look for the main header sctp.h in the sctp.framework.
If you compile code for OSX and Linux, you might have to do this

#ifdef __APPLE__
#include <sctp/sctp.h>
#else
#include <netinet/sctp.h>
#endif

A note about NKE under MacOS X. They are a bit tricky to build as you need a key which allows signing kernel extensions. Normal developer ID's can not (you have to specifically ask Apple for that).
The PKG I build has a signed version of the kernel extension. And it was built from the current source tree which is basically the same as Michael Tüxen's sctp source with the changes I mentioned.

make_pkg.sh is basically the shell script which takes the xcode build output, puts it into the right directory and makes a package out of it which you can install with the installer.
So this wii give you:

	/Library/Frameworks/sctp.framework/			the userspace shared library and its header file to compile against
	/Library/Extensions/SCTP.kext				the kernel extension
	/Library/Extensions/SCTPSupport.kext			an empty kernel extension exporting private functions which SCTP.kext needs
	/Library/Application Support/me.fink.sctp/startup_script.sh	a startup script to load SCTP.kext at startup
	/Library/LaunchDaemons/me.fink.sctp.plist		a launchctl file which triggers the startup script at load.


You might want to look at my ulibsctp project which uses my ulib.framework and the sctp.framework to use it from ObjectiveC.
I use it for our SMSC, STP and other SS7 signaling products which make mandatory use of SCTP. The use can be a bit tricky if you don't use SCTP in a "tcp client/server" stile but a peer to peer style.

**Comment by microup** [comment]
Hi Andreas,

I have the same error "ld: framework not found SCTP" on the Mac OS Catalina when building project ulib from https://github.com/andreasfink/ulib, I tried to do everything instruction as for Sierra and I can not load kext into the kernel of the system.

Thanks for the help!

**Comment by andreasfink** [comment]
There is no support for SCTP in catalina. The old kext driver for 10.14 doesnt yet run under 10.15. Apple has no plans to support kernel extensions much longer. The replacement technology they offer is NetworkExtensions. However SCTP can not be implemented with it as its not supporting incoming connections.

If you dont need SCTP you can disable its support in ulib (its linked optional).

if you run ./configure it should detect the presence or absence of libsctp

If you want to make use of sctp, open a developer feedback ("radar") with apple
--

**Comment by microup** [comment]
Thanks for the answer!

If I need to use SCTP, do I need to downgrade from Catalina to Mojave?

Can I build your libraries ulib and others libs included to SS7, under Xcode installed in Mojave?

What minimal version need XCode for building project ulib?

PS. I'm also new to macOS and ObjectiveC - how to disable libsctp in ulib?

BR

**Comment by andreasfink** [comment]
ulib runs on any MacOS X version since 10.8 up to the latest Catalina 10.16
It also runs under iOS and iPad OS and probably with some limitations under watchOS or tvOS
And it runs under Linux (Debian/Ubuntu) and should run on FreeBSD and other Unixes where you can get decent support for ObjectiveC 2.0 and GnuStep with ARC support.

ulib with SCTP only works on platforms which have (or can have SCTP).
The define SCTP_SUPPORTED is for enabling / disabling this.
Currently it assumes MacOS X has it. But you can commment this out in UMSocket.m

Support for SCTP is separated into ulibsctp but the bind call (or sctp_bindx call to be exact) was not separated yet.
I have updated the repo with the latest version. Thats the only dependency yet.

Note: ulibsctp depends on a recent openssl installation (not the one MacOS X comes with for compatibility reason which is very very old).
Prebuilt binaries are in the repository tree under libs/osx/openssl-1.1.1g-binary including build instructions.
These binaries are usually compiled with sctp support in them as static libraries only.

On Mojave you simply have to install the SCTP driver from https://github.com/andreasfink/macos_sctp_nke/
It has a pkg installer. You can not easily build that one yourself as kernel extensions need to be notarized and require special permissions to get loaded.
After installing the PKG and rebooting, you should see

kextstat | grep sctp

outputing something like this:

169 1 0xffffff7f80efd000 0x6510 0x6510 me.fink.sctpsupport (16.0.0) B660A413-27AA-4D40-AEB9-54C9359F4900
170 0 0xffffff7f83443000 0x60000 0x60000 me.fink.sctp (16.0.0) 6E0DB377-F3B0-35D3-9624-2B01927837D5 <169 8 6 5 1>

You can only have the userspace library installed in Catalina and compile and run everything even if the kernel extension doesnt load. but then sctp functions dont work but all the rest will.

**Comment by andreasfink** [comment]
PS: to answer the Xcode part of the question: The latet Xcode supported for your current platform is fine.
The project is defined to run on MacOS X 10.8 or newer so it should be backwards compatible up to 10.8. It used to run on 10.4 even.

Personally I run it under Xcode 11.6 on Catalina because I try to get a kext for Catalina working.
Its a bit tricky without having the up to date kernel sources yet. opensource.apple.com (http://opensource.apple.com) so far only goes to 10.15.3 while my Mac is already on 10.15.6.

**Comment by andreasfink** [comment]
sctp code now has been moved into ulibsctp.
so ulib should compile with or without sctp.framework being present.
